
const STORE_KEY="bearTravelPlanner_v5";
const OLD_KEYS=["bearTravelPlanner_v3","bearTravelPlanner_v2_full","bearTravelPlanner_v1_full","bearTravelPlannerV4","bearMultiTripV3","bearMultiTrip"];
const types=["🏯 景點","🏨 住宿","🍜 美食","🛍 購物","☕ 咖啡廳","🌃 夜景"];
const transports=["🚗 開車","🚶‍♀️ 走路","🚕 計程車","🚆 大眾交通","🚌 巴士"];
const currencies=["JPY","TWD","KRW","THB"];
const week=["SUN","MON","TUE","WED","THU","FRI","SAT"];
let state=loadState(), currentTripId=state.trips[0]?.id||null, currentTab=0, filterType="全部";
const app=document.getElementById("app"), tabsEl=document.getElementById("tabs"), subtitle=document.getElementById("subtitle"), modal=document.getElementById("modal"), modalBody=document.getElementById("modalBody"), backToTrips=document.getElementById("backToTrips");
backToTrips.onclick=()=>{currentTripId=null;currentTab=0;render()}; modal.onclick=e=>{if(e.target.id==="modal")closeModal()};

function defTrip(){return {id:Date.now()+Math.random(),name:"🍁 福岡 Autumn",date:"2026.10.10－10.14",startDate:"2026-10-10",members:["爸爸","媽媽","弟弟","妹妹","🐻","👦🏻"],rates:{JPY:.21,TWD:1,KRW:.023,THB:.9},flight:{go:{airline:"",no:"",from:"TPE",to:"FUK",time:"",duration:"",terminal:"",note:""},back:{airline:"",no:"",from:"FUK",to:"TPE",time:"",duration:"",terminal:"",note:""}},days:Array.from({length:5},()=>[]),expenses:[],splits:[],buy:[]}}
function loadState(){try{let raw=localStorage.getItem(STORE_KEY); if(!raw){for(const k of OLD_KEYS){raw=localStorage.getItem(k);if(raw)break}} const s=raw?JSON.parse(raw):{trips:[defTrip()]}; if(!s.trips?.length)s.trips=[defTrip()]; s.trips.forEach(norm); return s}catch{return{trips:[defTrip()]}}}
function norm(t){t.members||=[];t.rates||={JPY:.21,TWD:1,KRW:.023,THB:.9};t.days=(t.days&&t.days.length)?t.days:[[],[],[],[],[]];t.expenses||=[];t.splits||=[];t.buy||=[];t.startDate||=""; if(!t.flight)t.flight=defTrip().flight; if(typeof t.flight.go==="string")t.flight=defTrip().flight; ["go","back"].forEach(k=>{t.flight[k]||={};Object.assign(t.flight[k],{airline:t.flight[k].airline||"",no:t.flight[k].no||"",from:t.flight[k].from||(k==="go"?"TPE":"FUK"),to:t.flight[k].to||(k==="go"?"FUK":"TPE"),time:t.flight[k].time||"",duration:t.flight[k].duration||"",terminal:t.flight[k].terminal||"",note:t.flight[k].note||""})})}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
function trip(){return state.trips.find(t=>t.id==currentTripId)}
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function readImage(input,cb){const f=input.files&&input.files[0];if(!f)return cb("");const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)}
function toTWD(a,c){return Math.round(Number(a||0)*(trip().rates[c]||1))}
function openModal(h){modalBody.innerHTML=h;modal.classList.remove("hidden")}function closeModal(){modal.classList.add("hidden");modalBody.innerHTML=""}
function tabs(){if(!currentTripId)return["旅程"];const t=trip();return["總覽","航班",...t.days.map((_,i)=>`D${i+1}`),"記帳","分攤","必買"]}
function renderTabs(){tabsEl.innerHTML=tabs().map((x,i)=>`<button class="${i===currentTab?'active':''}" onclick="setTab(${i})">${x}</button>`).join("")}
function setTab(i){currentTab=i;filterType="全部";render()}
function render(){save();renderTabs();const t=trip();backToTrips.classList.toggle("hidden",!currentTripId);subtitle.textContent=currentTripId?`${t.name}｜${t.date||"未設定日期"}`:"Every journey becomes a beautiful memory. 🍂";if(!currentTripId){app.innerHTML=tripList();return} if(currentTab===0)app.innerHTML=overview();else if(currentTab===1)app.innerHTML=flight();else if(currentTab>=2&&currentTab<2+t.days.length)app.innerHTML=day(currentTab-2);else if(currentTab===2+t.days.length)app.innerHTML=expenses();else if(currentTab===3+t.days.length)app.innerHTML=splits();else app.innerHTML=buy()}
function dayDate(i){if(!trip().startDate)return{w:"DAY",d:i+1,full:`Day ${i+1}`};const d=new Date(trip().startDate+"T00:00:00");d.setDate(d.getDate()+i);return{w:week[d.getDay()],d:d.getDate(),full:`${d.getMonth()+1}/${d.getDate()}`}}
function itemClass(x){const s=x.type||"";if(s.includes("住宿"))return"stay";if(s.includes("美食"))return"food";if(s.includes("購物"))return"shop";if(s.includes("咖啡"))return"cafe";if(s.includes("夜景"))return"night";return""}

/* trips */
function tripList(){return `<section class="card"><h2>🧸 我的旅程</h2><input id="tn" placeholder="旅程名稱"><input id="td" placeholder="日期顯示"><input id="ts" type="date"><input id="tm" placeholder="旅伴，用逗號分隔"><input id="tnum" type="number" placeholder="天數"><button class="btn primary" onclick="addTrip()">新增旅程</button></section>${state.trips.map((t,i)=>`<section class="card trip-card"><div onclick="currentTripId=${t.id};currentTab=0;render()"><h2>${esc(t.name)}</h2><p>${esc(t.date)}</p><p class="small">${t.days.length} 天｜${t.members.join("、")}</p></div><button class="btn" onclick="editTrip(${i})">編輯</button><button class="btn danger" onclick="delTrip(${i})">刪除</button></section>`).join("")}`}
function addTrip(){const t=defTrip();t.name=tn.value||"未命名旅程";t.date=td.value||"";t.startDate=ts.value||"";t.members=tm.value?tm.value.split(",").map(x=>x.trim()).filter(Boolean):[];t.days=Array.from({length:Math.max(1,Number(tnum.value||5))},()=>[]);state.trips.push(t);currentTripId=t.id;currentTab=0;render()}
function editTrip(i){const t=state.trips[i];openModal(`<h2>編輯旅程</h2><input id="en" value="${esc(t.name)}"><input id="ed" value="${esc(t.date)}"><input id="es" type="date" value="${esc(t.startDate)}"><input id="em" value="${esc(t.members.join(","))}"><button class="btn primary" onclick="state.trips[${i}].name=en.value;state.trips[${i}].date=ed.value;state.trips[${i}].startDate=es.value;state.trips[${i}].members=em.value.split(',').map(x=>x.trim()).filter(Boolean);closeModal();render()">儲存</button>`)}
function delTrip(i){if(state.trips.length<=1)return alert("至少保留一趟旅程");if(confirm("刪除旅程？")){state.trips.splice(i,1);currentTripId=state.trips[0].id;render()}}

/* overview */
function overview(){const t=trip();return `<section class="trip-hero"><h2>${esc(t.name)}</h2><p>${esc(t.date)}</p><p>${t.days.length}天｜${t.members.length}位旅伴｜${t.days.flat().length}個行程</p></section><section class="card"><h3>旅伴設定</h3><input id="members" value="${esc(t.members.join(","))}"><button class="btn primary" onclick="trip().members=members.value.split(',').map(x=>x.trim()).filter(Boolean);render()">更新旅伴</button><h3>天數設定</h3><button class="btn dark" onclick="trip().days.push([]);render()">＋增加一天</button><button class="btn danger" onclick="removeDay()">－減少一天</button></section>`}
function removeDay(){if(trip().days.length<=1)return;if(confirm("刪除最後一天？")){trip().days.pop();render()}}

/* flight separate refined */
function flight(){const f=trip().flight;return `<section class="card"><h2>✈️ 航班頁</h2>${flightBlock("去程",f.go)}${flightFields("go",f.go)}${flightBlock("回程",f.back)}${flightFields("back",f.back)}<button class="btn primary" onclick="saveFlight()">儲存航班</button></section>`}
function flightBlock(title,x){return `<h3>${title}</h3><div class="flight-card"><b>${esc(x.airline||"航空公司")} ${esc(x.no||"航班號")}</b><div class="flight-route"><div><div class="airport">${esc(x.from||"TPE")}</div><small>出發</small></div><div class="arrow">→</div><div><div class="airport">${esc(x.to||"FUK")}</div><small>抵達</small></div></div><div class="flight-info"><div>航班時間<b>${esc(x.time||"未填")}</b></div><div>飛行時間<b>${esc(x.duration||"未填")}</b></div><div>航廈<b>${esc(x.terminal||"未填")}</b></div><div>備註<b>${esc(x.note||"—")}</b></div></div></div>`}
function flightFields(p,x){return `<input id="${p}Airline" placeholder="航空公司" value="${esc(x.airline)}"><input id="${p}No" placeholder="航班號" value="${esc(x.no)}"><div class="grid"><input id="${p}From" placeholder="出發機場代碼" value="${esc(x.from)}"><input id="${p}To" placeholder="抵達機場代碼" value="${esc(x.to)}"></div><input id="${p}Time" placeholder="航班時間" value="${esc(x.time)}"><input id="${p}Duration" placeholder="飛行時間" value="${esc(x.duration)}"><input id="${p}Terminal" placeholder="航廈" value="${esc(x.terminal)}"><textarea id="${p}Note" placeholder="備註">${esc(x.note)}</textarea>`}
function saveFlight(){trip().flight={go:{airline:goAirline.value,no:goNo.value,from:goFrom.value,to:goTo.value,time:goTime.value,duration:goDuration.value,terminal:goTerminal.value,note:goNote.value},back:{airline:backAirline.value,no:backNo.value,from:backFrom.value,to:backTo.value,time:backTime.value,duration:backDuration.value,terminal:backTerminal.value,note:backNote.value}};render()}

/* itinerary new page style */
function day(i){const t=trip(),dd=dayDate(i),list=t.days[i],shown=filterType==="全部"?list:list.filter(x=>(x.type||"").includes(filterType));return `<section class="trip-hero"><h2>${esc(t.name)}</h2><p>${esc(t.date)}</p><div class="date-strip">${t.days.map((_,idx)=>{const d=dayDate(idx);return `<div class="date-chip ${idx===i?'active':''}" onclick="setTab(${idx+2})"><b>${d.w}</b><span>${d.d}</span></div>`}).join("")}</div><div class="weather"><div>⛅</div><div><div class="temp">--°C</div><div class="small">可自行於備註記錄天氣</div></div></div></section><div class="filters">${["全部","景點","住宿","美食","購物","航班"].map(f=>`<button class="${filterType===f?'on':''}" onclick="filterType='${f}';render()">${f}</button>`).join("")}</div><section class="card"><h2>${dd.full} (${dd.w})　Day ${i+1}</h2><button class="btn primary" onclick="openItForm(${i})">＋新增行程</button></section>${!shown.length?`<section class="card empty">這個分類還沒有行程 🍂</section>`:`<div class="timeline">${shown.map((x,idx)=>card(x,list.indexOf(x),i,list)).join("")}</div>`}`}
function card(x,i,d,list){const move=i<list.length-1?`<div class="move-line">${esc(x.trans||"🚗 開車")} 約 ${esc(x.moveTime||"未填")} ${x.moveRange?`・${esc(x.moveRange)}`:""}</div>`:"";return `<section class="it-card ${itemClass(x)}" draggable="true" ondragstart="window.dragIndex=${i}" ondragover="event.preventDefault()" ondrop="dropItem(${d},${i})"><div class="it-head">${x.photo?`<img class="pic" src="${x.photo}">`:""}<div class="it-body"><div class="right-time">${esc(x.arrive||"")}</div><div class="it-title">${esc(x.name||"未命名")}</div><div class="chips"><span class="chip">${esc(x.type||"景點")}</span>${x.stay?`<span class="chip">⏱ ${esc(x.stay)}</span>`:""}</div>${x.memo?`<p class="note">${esc(x.memo)}</p>`:""}${x.map?`<p><a href="${esc(x.map)}" target="_blank">📍 導航</a></p>`:""}<select class="drag-select" onchange="moveTo(${d},${i},this.value)">${list.map((_,j)=>`<option value="${j}" ${i===j?"selected":""}>移到第 ${j+1} 個</option>`).join("")}</select><button class="btn" onclick="editItem(${d},${i})">編輯</button><button class="btn danger" onclick="delItem(${d},${i})">刪除</button></div></div></section>${move}`}
function form(x={},action){return `<h2>${x.name?"編輯":"新增"}行程</h2><select id="itType">${types.map(v=>`<option ${v===x.type?"selected":""}>${v}</option>`).join("")}</select><input id="itName" placeholder="名稱" value="${esc(x.name)}"><input id="itMap" placeholder="Google Maps連結" value="${esc(x.map)}"><div class="grid"><input id="itArrive" placeholder="抵達時間" value="${esc(x.arrive)}"><input id="itStay" placeholder="停留時間" value="${esc(x.stay)}"></div><select id="itTrans">${transports.map(v=>`<option ${v===x.trans?"selected":""}>${v}</option>`).join("")}</select><input id="itMove" placeholder="到下一站時間，例如 25分鐘" value="${esc(x.moveTime)}"><input id="itRange" placeholder="移動時段，例如 09:30→09:55" value="${esc(x.moveRange)}"><textarea id="itMemo" placeholder="備註">${esc(x.memo)}</textarea>${x.photo?`<img class="pic" src="${x.photo}">`:""}<input id="itPhoto" type="file" accept="image/*"><button class="btn primary" onclick="${action}">儲存</button>`}
function openItForm(d){openModal(form({},`addItem(${d})`))}
function addItem(d){readImage(itPhoto,photo=>{trip().days[d].push({type:itType.value,name:itName.value,map:itMap.value,arrive:itArrive.value,stay:itStay.value,trans:itTrans.value,moveTime:itMove.value,moveRange:itRange.value,memo:itMemo.value,photo});closeModal();render()})}
function editItem(d,i){openModal(form(trip().days[d][i],`saveItem(${d},${i})`))}
function saveItem(d,i){const x=trip().days[d][i];readImage(itPhoto,photo=>{Object.assign(x,{type:itType.value,name:itName.value,map:itMap.value,arrive:itArrive.value,stay:itStay.value,trans:itTrans.value,moveTime:itMove.value,moveRange:itRange.value,memo:itMemo.value});if(photo)x.photo=photo;closeModal();render()})}
function delItem(d,i){if(confirm("刪除行程？")){trip().days[d].splice(i,1);render()}}
function dropItem(d,i){const arr=trip().days[d];if(window.dragIndex==null)return;const it=arr.splice(window.dragIndex,1)[0];arr.splice(i,0,it);window.dragIndex=null;render()}
function moveTo(d,from,to){to=Number(to);if(from===to)return;const arr=trip().days[d],it=arr.splice(from,1)[0];arr.splice(to,0,it);render()}

/* other pages compact */
function rateBox(){const t=trip();return `<section class="card"><h3>匯率設定</h3>${currencies.map(c=>`<label>${c}<input type="number" step="0.001" value="${t.rates[c]}" onchange="trip().rates['${c}']=Number(this.value);render()"></label>`).join("")}</section>`}
function expenses(){const t=trip(),tot={JPY:0,TWD:0,KRW:0,THB:0};let total=0;t.expenses.forEach(x=>{tot[x.cur]+=Number(x.amount||0);total+=toTWD(x.amount,x.cur)});return `${rateBox()}<section class="card"><h2>💰 記帳</h2><div class="grid">${currencies.map(c=>`<div class="card"><b>${c}</b><div class="money">${tot[c]}</div></div>`).join("")}</div><div class="card"><b>約台幣總額</b><div class="money">NT$ ${total}</div></div><input id="exName" placeholder="項目名稱"><input id="exAmount" type="number" placeholder="金額"><select id="exCur">${currencies.map(c=>`<option>${c}</option>`).join("")}</select><textarea id="exMemo" placeholder="備註"></textarea><input id="exReceipt" type="file" accept="image/*"><button class="btn primary" onclick="addExpense()">新增</button></section>${t.expenses.map((x,i)=>`<section class="card">${x.receipt?`<img class="pic" src="${x.receipt}">`:""}<h3>${esc(x.name)}</h3><div class="money">${x.amount} ${x.cur}</div><p>約 NT$ ${toTWD(x.amount,x.cur)}</p><button class="btn danger" onclick="trip().expenses.splice(${i},1);render()">刪除</button></section>`).join("")}`}
function addExpense(){readImage(exReceipt,receipt=>{trip().expenses.push({name:exName.value,amount:exAmount.value,cur:exCur.value,memo:exMemo.value,receipt});render()})}
function splits(){const t=trip(),tot={};currencies.forEach(c=>tot[c]={});t.members.forEach(m=>currencies.forEach(c=>tot[c][m]=0));t.splits.forEach(x=>x.people.forEach(p=>tot[x.cur][p]+=Number(x.amount||0)/x.people.length));return `${rateBox()}<section class="card"><h2>👨‍👩‍👧‍👦 分攤</h2>${currencies.map(c=>`<h3>${c}</h3><div class="grid">${t.members.map(m=>`<div class="card"><b>${esc(m)}</b><div class="money">${Math.round(tot[c][m]||0)} ${c}</div></div>`).join("")}</div>`).join("")}<input id="spName" placeholder="項目"><input id="spAmount" type="number" placeholder="總金額"><select id="spCur">${currencies.map(c=>`<option>${c}</option>`).join("")}</select><div class="people-box">${t.members.map(m=>`<label class="tag"><input type="checkbox" name="sp" value="${esc(m)}"> ${esc(m)}</label>`).join("")}</div><button class="btn primary" onclick="addSplit()">新增</button></section>${t.splits.map((x,i)=>`<section class="card"><h3>${esc(x.name)}</h3><p>${x.amount} ${x.cur}｜${x.people.join("、")}</p><button class="btn danger" onclick="trip().splits.splice(${i},1);render()">刪除</button></section>`).join("")}`}
function addSplit(){const people=[...document.querySelectorAll("input[name=sp]:checked")].map(x=>x.value);if(!people.length)return alert("請勾選成員");trip().splits.push({name:spName.value,amount:spAmount.value,cur:spCur.value,people});render()}
function buy(){const t=trip(),g={};t.buy.forEach((x,i)=>{const a=x.area||"未分類";if(!g[a])g[a]=[];g[a].push({...x,i})});return `<section class="card"><h2>🛍 必買</h2><input id="buyName" placeholder="商品名稱"><input id="buyArea" placeholder="地區／會經過的地方"><textarea id="buyMemo" placeholder="備註"></textarea><input id="buyPic" type="file" accept="image/*"><button class="btn primary" onclick="addBuy()">新增</button></section>${Object.keys(g).sort().map(a=>`<h3 class="area-title">${esc(a)}</h3><div class="grid">${g[a].map(x=>`<section class="card">${x.pic?`<img class="pic" src="${x.pic}">`:""}<h3>${esc(x.name)}</h3><p>${esc(x.memo)}</p><button class="btn danger" onclick="trip().buy.splice(${x.i},1);render()">刪除</button></section>`).join("")}</div>`).join("")}`}
function addBuy(){readImage(buyPic,pic=>{trip().buy.push({name:buyName.value,area:buyArea.value||"未分類",memo:buyMemo.value,pic});render()})}
render();
